### ISSUE TITLE
ModuleNotFoundError: No module named 'auth'

### ISSUE THREAD

**Issue by jiangwu10057** [coze-dev/coze-py#51]
Traceback (most recent call last):
  File "/Users/miluyu/Documents/develop/coze.py", line 1, in <module>
    from cozepy import Coze, TokenAuth
  File "/usr/local/lib/python3.9/site-packages/cozepy/__init__.py", line 1, in <module>
    from auth import Auth, PersonalAccessToken
ModuleNotFoundError: No module named 'auth'

**Comment by chyroc** [comment]
please upgrade to v0.2.0: `pip install -U cozepy`
