### ISSUE TITLE
httpx.ConnectError: [Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by jiangwu10057** [coze-dev/coze-py#59]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/miluyu/Documents/develop/coze.py", line 6, in <module>
    result = coze.workflows.runs.create(
  File "/usr/local/lib/python3.9/site-packages/cozepy/workflows/runs/__init__.py", line 163, in create
    return self._requester.request("post", url, WorkflowRunResult, body=body)
  File "/usr/local/lib/python3.9/site-packages/cozepy/request.py", line 74, in request
    response = self._client.send(request, stream=stream)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/Cellar/python@3.9/3.9.18_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 54] Connection reset by peer

**Comment by jiangwu10057** [comment]
cn:
coze = Coze(auth=TokenAuth(""), base_url='https://api.coze.cn')

**Comment by chyroc** [comment]
you can use COZE_CN_BASE_URL const
